# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

glm_elnet_c <- function(x, pseudo_obs, lambda, alpha, intercept, thresh, qa_updates_max, pmax, pmax_strict, as_updates_max = 50L) {
    .Call('projpred_glm_elnet_c', PACKAGE = 'projpred', x, pseudo_obs, lambda, alpha, intercept, thresh, qa_updates_max, pmax, pmax_strict, as_updates_max)
}

glm_ridge_c <- function(x, pseudo_obs, lambda, intercept, thresh, qa_updates_max, ls_iter_max = 100L) {
    .Call('projpred_glm_ridge_c', PACKAGE = 'projpred', x, pseudo_obs, lambda, intercept, thresh, qa_updates_max, ls_iter_max)
}

